---
apiVersion: v1
kind: Service
metadata:
  name: consumer-device1
  labels:
    app: consumer-device1
spec:
  type: NodePort
  ports:
  - name: "consumer-device1"
    port: 3333
    nodePort: 32111
  selector:
    app: consumer-device1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-device1
spec:
  selector:
    matchLabels:
      app: consumer-device1
  template:
    metadata:
      labels:
        app: consumer-device1
    spec:
      containers:
      - name: consumer-device1
        image: lshyeung/consumer-device1
        ports:
        - containerPort: 3333

